
# cargo-vet audits file

[[audits.quick_cache]]
who = "Emmanuel Keller <emmanuel.keller@surrealdb.com>"
criteria = "safe-to-deploy"
version = "0.5.1"

[[audits.rustls]]
who = "Tobie Morgan Hitchcock <tobie@surrealdb.com>"
criteria = "safe-to-deploy"
delta = "0.21.10 -> 0.21.11"

[[audits.rustls]]
who = "Tobie Morgan Hitchcock <tobie@surrealdb.com>"
criteria = "safe-to-deploy"
delta = "0.22.3 -> 0.22.4"

[[trusted.addr]]
criteria = "safe-to-deploy"
user-id = 3987 # Rushmore Mushambi (rushmorem)
start = "2021-02-25"
end = "2025-01-24"

[[trusted.anyhow]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-10-05"
end = "2025-08-06"

[[trusted.async-trait]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-07-23"
end = "2025-08-06"

[[trusted.dmp]]
criteria = "safe-to-deploy"
user-id = 145457 # Tobie Morgan Hitchcock (tobiemh)
start = "2022-01-27"
end = "2025-01-24"

[[trusted.echodb]]
criteria = "safe-to-deploy"
user-id = 145457 # Tobie Morgan Hitchcock (tobiemh)
start = "2022-01-27"
end = "2025-01-24"

[[trusted.hashbrown]]
criteria = "safe-to-deploy"
user-id = 2915 # Amanieu d'Antras (Amanieu)
start = "2019-04-02"
end = "2025-05-02"

[[trusted.indxdb]]
criteria = "safe-to-deploy"
user-id = 145457 # Tobie Morgan Hitchcock (tobiemh)
start = "2022-02-19"
end = "2025-01-24"

[[trusted.lexicmp]]
criteria = "safe-to-deploy"
user-id = 145457 # Tobie Morgan Hitchcock (tobiemh)
start = "2023-03-26"
end = "2025-01-24"

[[trusted.paste]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-19"
end = "2025-08-06"

[[trusted.prettyplease]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2022-01-04"
end = "2025-08-06"

[[trusted.psl-types]]
criteria = "safe-to-deploy"
user-id = 3987 # Rushmore Mushambi (rushmorem)
start = "2021-03-12"
end = "2025-01-24"

[[trusted.ref-cast]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-05"
end = "2025-08-06"

[[trusted.ref-cast-impl]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-05"
end = "2025-08-06"

[[trusted.revision]]
criteria = "safe-to-deploy"
user-id = 145457 # Tobie Morgan Hitchcock (tobiemh)
start = "2023-08-09"
end = "2025-01-24"

[[trusted.revision-derive]]
criteria = "safe-to-deploy"
user-id = 145457 # Tobie Morgan Hitchcock (tobiemh)
start = "2023-08-09"
end = "2025-01-24"

[[trusted.ryu]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2025-08-06"

[[trusted.serde_bytes]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-02-25"
end = "2025-08-06"

[[trusted.serde_json]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-02-28"
end = "2025-08-06"

[[trusted.serde_path_to_error]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-08-20"
end = "2025-08-06"

[[trusted.storekey]]
criteria = "safe-to-deploy"
user-id = 145457 # Tobie Morgan Hitchcock (tobiemh)
start = "2022-03-16"
end = "2025-01-24"

[[trusted.surrealdb]]
criteria = "safe-to-deploy"
user-id = 145457 # Tobie Morgan Hitchcock (tobiemh)
start = "2022-07-19"
end = "2025-01-24"

[[trusted.surrealdb-core]]
criteria = "safe-to-deploy"
user-id = 145457 # Tobie Morgan Hitchcock (tobiemh)
start = "2024-01-30"
end = "2025-01-24"

[[trusted.surrealdb-derive]]
criteria = "safe-to-deploy"
user-id = 145457 # Tobie Morgan Hitchcock (tobiemh)
start = "2022-02-26"
end = "2025-01-24"

[[trusted.surrealdb-jsonwebtoken]]
criteria = "safe-to-deploy"
user-id = 3987 # Rushmore Mushambi (rushmorem)
start = "2023-08-29"
end = "2025-01-24"

[[trusted.surrealdb-tikv-client]]
criteria = "safe-to-deploy"
user-id = 217605 # Yusuke Kuoka (mumoshu)
start = "2023-06-19"
end = "2025-07-08"

[[trusted.surrealkv]]
criteria = "safe-to-deploy"
user-id = 145457 # Tobie Morgan Hitchcock (tobiemh)
start = "2024-02-08"
end = "2025-02-10"

[[trusted.surrealml-core]]
criteria = "safe-to-deploy"
user-id = 145457 # Tobie Morgan Hitchcock (tobiemh)
start = "2023-10-31"
end = "2025-01-24"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2025-08-06"

[[trusted.trice]]
criteria = "safe-to-deploy"
user-id = 145457 # Tobie Morgan Hitchcock (tobiemh)
start = "2022-02-17"
end = "2025-01-24"

[[trusted.vart]]
criteria = "safe-to-deploy"
user-id = 145457 # Tobie Morgan Hitchcock (tobiemh)
start = "2024-01-16"
end = "2025-02-10"
